### ISSUE TITLE
Can you give example build setup?

### ISSUE THREAD

**Issue by t-rekttt** [nomi-san/parsec-vdd#1]
I like your idea but couldn't figure out how to implement it as you described, so a simple build setup from your description would help alot

**Comment by nomi-san** [comment]
The sample code in the README is all you need, but it needs some editing to make it works.
It's just a win32 program that controls VDD using DeviceIoControl api.

First, you need to get the VDD handle. The following uses hardcoded file path.

```cpp
auto path = "\\\\?\\root#display#0001#{00b41627-04c4-429e-a26e-0265cf50c8fa}";
auto vdd = CreateFileA(path, GENERIC_READ | GENERIC_WRITE, 0, NULL, OPEN_EXISTING, 0, NULL);
```
- `0001` is VDD index, note that 4 digits

Next, connect to the VDD and plug in a monitor.
```cpp
VddIoCtl(vdd, IOCTL_VDD_CONNECT);
VddIoCtl(vdd, IOCTL_VDD_UPDATE);
VddIoCtl(vdd, IOCTL_VDD_ADD);
VddIoCtl(vdd, IOCTL_VDD_UPDATE);
```

Then run this loop to keep the monitor connection.

```cpp
while (running) {
    Sleep(100);
    VddIoCtl(vdd, IOCTL_VDD_UPDATE);
}
```
- It also can be run in a parallel thread

Finally, reconnect to unplug the monitor.

```cpp
VddIoCtl(vdd, IOCTL_VDD_CONNECT);
CloseHandle(vdd);
```

```mermaid
graph TD
A[controller.exe]
B[ParsecVDD adapter]
X[IOCTL_VDD_CONNECT]
Y[IOCTL_VDD_ADD]
Z[IOCTL_VDD_UPDATE]

A --- X --> |connect/disconnect|B
A --- Y --> |plug in|B
A --- Z --> |update conn|B
```

**Comment by t-rekttt** [comment]
Last week I tried to build but ran into this error, I remember looking around for solutions but eventually didn't know how to solve it at all
![image](https://user-images.githubusercontent.com/9071846/225368520-a9dfb07f-a605-4242-b8d8-72da0937da55.png)

**Comment by t-rekttt** [comment]
Information on VS Installer:
![image](https://user-images.githubusercontent.com/9071846/225370436-fe5e8cff-f0a1-47d7-95d9-25e28ef31621.png)

**Comment by nomi-san** [comment]
> Last week I tried to build but ran into this error, I remember looking around for solutions but eventually didn't know how to solve it at all

This RustDeskIddDriver is a user-mode driver, you need to install Windows Driver Kit.
https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by t-rekttt** [comment]
> 

I did tried to install it but I'm using Windows 10, seems like it's not working

**Comment by t-rekttt** [comment]
> > Last week I tried to build but ran into this error, I remember looking around for solutions but eventually didn't know how to solve it at all
> 
> This RustDeskIddDriver is a user-mode driver, you need to install Windows Driver Kit. https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

I did tried to install it but I'm using Windows 10, seems like it's not working

**Comment by nomi-san** [comment]
No, Windows 10 is not the problem.
You also can build it with VS2017/19 + Win10 WDK.

https://www.techspot.com/downloads/6278-visual-studio.html
https://learn.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads

Btw, I think you're going so far.
If you need to create your own VDD, so RustDeskIddDriver or any similar is fine, then open issue on its repo.
With my repo, there is no need to make a driver!

**Comment by t-rekttt** [comment]
So you mean that I don't need to actually build the who driver, but instead just to take the `DeviceOpenHandle` function you referenced? 
Looking into that function I thought that it will need some dependencies more than just the function itself, so that's why I decided to build the whole repo and try to patch some code after that instead of just trying to pick that function (I expect to run into more errors if I do that)

**Comment by nomi-san** [comment]
I just created a demo with edited `DeviceOpenHandle(GUID)`, it's a simple win32 application, no driver or WDK needed.
https://github.com/nomi-san/parsec-vdd/blob/main/demo.cc

Any question please DM me via mess.

**Comment by monokaijs** [comment]
Ai cho close?

**Comment by monokaijs** [comment]
@nomi-san open lại cãi nhau tí xem nào

**Comment by nomi-san** [comment]
![image](https://github.com/nomi-san/parsec-vdd/assets/38210249/d39a6cc9-8cc8-4931-9e9c-94b12c94960b)
