### ISSUE TITLE
Todo: Parsec VDD v0.45 support

### ISSUE THREAD

**Issue by nomi-san** [nomi-san/parsec-vdd#11]
Parsec has announced VDD v0.45 in early of March.
https://builds.parsec.app/vdd/parsec-vdd-0.45.0.0.exe

> Parsec Virtual Display Driver 0.45 allows you to select which physical GPU you wish the adapter to spawn on. This change is aimed at virtual machines and the selection can be changed using the Windows Registry.

> Parsec Virtual Display Driver 0.45 greatly improves Privacy Mode and Virtual Display Driver reliability when used in combination with 150-93.

Seems the Privacy Mode bug (mentioned in README) has been fixed. And the driver setup (installer) is now using **nefconw** (by [nefarius](https://github.com/nefarius/nefcon)) instead of **MS devcon**. That will fix a problem that devcon cannot fully uninstall/override the driver files (mm.dll).

```bat
nefconw --remove-device-node --hardware-id Root\Parsec\VDA --class-guid "4D36E968-E325-11CE-BFC1-08002BE10318"
nefconw --create-device-node --class-name Display --class-guid "4D36E968-E325-11CE-BFC1-08002BE10318" --hardware-id Root\Parsec\VDA
nefconw --install-driver --inf-path ".\driver\mm.inf"
```

<br>

Sorry for my late, the ParsecVDisplay app will be released soon in **the end of this month** and should support VDD v0.45.

**Comment by hallfay0** [comment]
Waited for a long time

**Comment by bthulu** [comment]
is there exists any release before?

**Comment by nomi-san** [comment]
@bthulu 
> is there exists any release before?

Not yet, but you can try some forks that have binary download:

- [KtzeAbyss/Easy-Virtual-Display](https://github.com/KtzeAbyss/Easy-Virtual-Display) (early stage of the project)
- [VergilGao/vddswitcher](https://github.com/VergilGao/vddswitcher)
- [timminator/ParsecVDA-Always-Connected](https://github.com/timminator/ParsecVDA-Always-Connected)
