### ISSUE TITLE
[False positive] Microsoft Defender Antivirus Flagging ParsecVDisplay as Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by qianxuu** [nomi-san/parsec-vdd#16]
I have observed that Microsoft Defender Antivirus is flagging [ParsecVDisplay v0.45-a](https://github.com/nomi-san/parsec-vdd/releases/tag/v0.45-a) as Trojan:Script/Wacatac.B!ml and has isolated related files. Below are the detailed information:

Severity: Severe

Detected: Trojan:Script/Wacatac.B!ml
Status: Isolated
Isolated file location: Restricted area, won't harm the device

Date: March 30, 2024, 10:00 AM
Details: According to the report, the program might contain malicious code possibly intended for executing commands from attackers.

Affected Items:
File: c:\program files\parsecvdisplay\parsecvdisplay.exe
File: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\ParsecVDisplay.lnk
File: C:\Users\Public\Desktop\ParsecVDisplay.lnk

**Comment by nomi-san** [comment]
That's average of open sourced software, please see the note when download.
> Note that the application is not signed, so it could be flagged as malware.

You should add the program to Exclusive. If dont trust it's safe, please build the [app](https://github.com/nomi-san/parsec-vdd/tree/main/app) from source.

**Comment by qianxuu** [comment]
> That's average of open sourced software, please see the note when download.
> 
> > Note that the application is not signed, so it could be flagged as malware.
> 
> You should add the program to Exclusive. If dont trust it's safe, please build the [app](https://github.com/nomi-san/parsec-vdd/tree/main/app) from source.

I'm sorry, I missed this information while downloading the software.
I trust that this software is safe, and it would be even better if the false positive virus detection issue could be resolved.
