### ISSUE TITLE
Load added displays on startup - 怎么在启动的时候默认增加一个屏幕呢

### ISSUE THREAD

**Issue by name-jerry** [nomi-san/parsec-vdd#17]
如题,开机启动的同时,默认设置一个虚拟屏幕

**Comment by nomi-san** [comment]
This feature is planned and will be added in next patch.
Ref #15

**Comment by name-jerry** [comment]
非常感谢，之前没注意到这条

**Comment by amazinghjj** [comment]
> This feature is planned and will be added in next patch. Ref #15

The next update will release the relevant commented code and then the feature will be supported by default, right?
