### ISSUE TITLE
vdd sans parsec wrap ?

### ISSUE THREAD

**Issue by jeanlaurentdotme** [nomi-san/parsec-vdd#2]
Bonjour, est ce que ce repo explique comment utiliser un VDD avec parsec sans souscrire à leurs offre wrap ?

**Comment by nomi-san** [comment]
No, this is a standalone use of VDD, without the Parsec app.
But you can add a virtual monitor to be used in your Parsec host.

**Comment by jeanlaurentdotme** [comment]
merci
