### ISSUE TITLE
Cannot start software after restarting computer

### ISSUE THREAD

**Issue by ferryvan** [nomi-san/parsec-vdd#21]
After I installed it, I ran it directly with no problems. However, after restarting the computer, the software did not start with the restart, and it could not be started by double-clicking the software icon.

Virtual display adapter can be seen in device manager

A temporary solution is to reinstall the software after a reboot. But when operating remotely, I had to start RDP to complete the reinstall before continuing to stream remotely using the virtual display

**Comment by nomi-san** [comment]
I think your main display is set to a virtual display (not your physical monitor). So double clicking on the tray icon will put the app window onto this main display. In that case, you should duplicate these screens or use Window + Arrow keys to move windows between screens.

**Comment by nomi-san** [comment]
Wait, if you start the program from desktop/startmenu icon then it will not launch or not show in taskbar, please reproduce this issue with a screen record video.

**Comment by ferryvan** [comment]
https://github.com/nomi-san/parsec-vdd/assets/40734586/cc512bd9-dfe5-4904-ae26-345d4df73b2a

Here is a screen record video that reproduces the problem

**Comment by nomi-san** [comment]
I see, seems the program does not start after restart, and works normally after new install.
If you have Visual Studio, you can switch to portable version and debug it (after restart) then report me the error.

**Comment by andreasbleck** [comment]
I'm having the same issue, my computer doesn't have any physical display attached and I use steam link to see the screen on a projector, the software doesn't start after booting the pc, making the resolution limited to a very low res, but if I connet via parsec from my mobile it starts working and I can start the software to have the virtual display and use a higher resolution, I don't need to stay connected via parsec, just a quick connect and disconnect makes the software work normally
