### ISSUE TITLE
can i just set the virtual screen as the main screen only?

### ISSUE THREAD

**Issue by LGJisRich** [nomi-san/parsec-vdd#22]
How about adding only the virtual screen display in windows settings?The settings only function as a copy of the physical screen and extend the physical screen,can i just set the virtual screen as the main screen only?Similar to the privacy mode?

**Comment by nomi-san** [comment]
> can i just set the virtual screen as the main screen only?

Yesh, you need to extend physical display -> virtual display first, then set the virtual display as main and disconnect other physical displays.
