### ISSUE TITLE
Does the virtual display not support connecting to a laptop's discrete graphics card with direct-connect mode turned on, but only supports connecting to the core graphics card of the CPU?

### ISSUE THREAD

**Issue by univers629** [nomi-san/parsec-vdd#24]
When I use sunshine on my laptop, because sunshine states "If a GPU is specified above, the monitor must be connected to that GPU." This causes my sunshine to run normally when using the laptop's cpu core graphics card. When using the independent graphics direct connection mode, it seems that the virtual monitor is not connected to the independent graphics card, resulting in an error when using sunshine for streaming.

**Comment by nomi-san** [comment]
ParsecVDD v0.45 has introduced an ability to set the parent GPU, check out this official guide.
https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu

**Comment by univers629** [comment]
Thank you very much for your reply. I found that my virtual monitor was able to connect to the Nvidia discrete graphics card, but I found a new problem. If you have time and are interested, you can take a look:https://github.com/LizardByte/Sunshine/discussions/2417
![PixPin_2024-04-14_09-16-44](https://github.com/nomi-san/parsec-vdd/assets/111641284/bcd632e0-bbc1-41df-99b9-5535aeb70e34)

**Comment by nomi-san** [comment]
```
[2024:04:14:09:22:06]: Info: ddprobe.exe [1] [\.\DISPLAY57] returned: 0x00000000
[2024:04:14:09:22:06]: Info: Set GPU preference: 1
[2024:04:14:09:22:07]: Error: Failed to locate an output device
[2024:04:14:09:22:07]: Error: Failed to locate an output device
```

Yeah I see, it could be a problem of vdd, but let's  wait for response from Sunshine.

**Comment by univers629** [comment]
> ```
> [2024:04:14:09:22:06]: Info: ddprobe.exe [1] [\.\DISPLAY57] returned: 0x00000000
> [2024:04:14:09:22:06]: Info: Set GPU preference: 1
> [2024:04:14:09:22:07]: Error: Failed to locate an output device
> [2024:04:14:09:22:07]: Error: Failed to locate an output device
> ```
> 
> 是的，我明白了，这可能是 vdd 的问题，但让我们等待 Sunshine 的回复。

Sunshine的回复似乎没有作用，我用ddprobe.exe测试确实得到了0的结果，我不明白nomi-san想表达什么，看起来似乎vdd事实上并没有连接到独立显卡，因为在nvidia的控制面板里只显示连接了一个笔记本的便捷显示屏😥

**Comment by nomi-san** [comment]
Then have you tried it?
> ParsecVDD v0.45 has introduced an ability to set the parent GPU, check out this official guide.
https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu

**Comment by univers629** [comment]
![屏幕截图 2024-05-02 105316](https://github.com/nomi-san/parsec-vdd/assets/111641284/d433b222-3ab2-4ffa-a4c5-9c5910a8188b)
![屏幕截图 2024-05-02 105927](https://github.com/nomi-san/parsec-vdd/assets/111641284/6fef39ef-938c-4c40-9103-c5dcedfec0f4)


> Then have you tried it?
> 
> > ParsecVDD v0.45 has introduced an ability to set the parent GPU, check out this official guide.
> > https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu

我成功了，我是傻逼🤣，上次用这个网页里的方法的时候没有发现注册表里有一项disablechange的值，把它改为0就好了，不过在独显直连模式串流moonlight还是会有“Connection terminated, no video received from host, please check your firewall and port forwarding rules Ports in: UDP 47998 UDP 48000”的报错，黑屏接收不到画面，不过我不咋用独显直连模式，就不管这个了😉
