### ISSUE TITLE
虚拟显示器不显示

### ISSUE THREAD

**Issue by Lee8213** [nomi-san/parsec-vdd#26]
![虚拟屏幕不显示](https://github.com/nomi-san/parsec-vdd/assets/52365977/e308c8d6-6c0f-408a-91a4-6b3882a68aa4)

在阳光用命令行退出串流切换显示器后，虚拟显示屏就不显示分辨率了，也不能正常使用。已经重新卸载和安装，问题依旧。

**Comment by nomi-san** [comment]
That means the display is set offline/disconnected and cant change any settings.

**Comment by Joker-ZXR** [comment]
我也是相同的问题，一直是offine，后面直接ADD DISPLAY没反应

**Comment by nomi-san** [comment]
> 我也是相同的问题，一直是offine，后面直接ADD DISPLAY没反应

Try the latest build here: https://github.com/nomi-san/parsec-vdd/actions/runs/15843539359

**Comment by thunder-sword** [comment]
same question

**Comment by ChubbyPaw** [comment]
我的是win11系统，在设置->系统->屏幕里选择offline的屏幕，然后设置成将桌面扩展到此显示器就解决了。

**Comment by riyauga** [comment]
我也是，且切不了扩展到此屏幕
