### ISSUE TITLE
parsec-vdd cannot add a virtual screen when connecting to microsoft remote desktop? Is this normal?

### ISSUE THREAD

**Issue by xzhonour** [nomi-san/parsec-vdd#28]
![image](https://github.com/nomi-san/parsec-vdd/assets/26564811/2befdc2f-1eac-46d6-a0e0-57d71e28443d)
![image](https://github.com/nomi-san/parsec-vdd/assets/26564811/91ccb503-905c-423f-85ab-bfa6bcb8476a)

parsec-vdd cannot add a virtual screen when connecting to microsoft remote desktop? Is this normal? The physical display has been disconnected！

**Comment by nomi-san** [comment]
Have you tried pressing the **Reload** 🔄 button? In case of the **Add Display** button is disabled, that means the fetching display info operation is stuck. Try using the right click menu in tray icon.

**Comment by xzhonour** [comment]
![image](https://github.com/nomi-san/parsec-vdd/assets/26564811/a039337e-1d1c-4f72-9fad-867b6b93a958)
I tried reloading, but it still cannot be added when clicked. The picture above is the software right-click menu.

**Comment by xzhonour** [comment]
![image](https://github.com/nomi-san/parsec-vdd/assets/26564811/23cb2a41-8fc1-4a1b-bdc0-f0cf76f2d826)

Virtual displays can be created normally when linking physical displays！

**Comment by kawanoii** [comment]
Same here, nothing happened after click 'ADD DISPLAY'. I was trying to attach a display to a GPU virtual machine.  but the provider only gives RDP access.  the only display attached is created by the RDP session. 

C:\Program Files\Sunshine\tools>dxgi-info.exe
====== ADAPTER =====
Device Name      : Microsoft Basic Render Driver
Device Vendor ID : 0x00001414
Device Device ID : 0x0000008C
Device Video Mem : 0 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 30719 MiB

    ====== OUTPUT ======
    Output Name       : \\.\DISPLAY1
    AttachedToDesktop : yes
    Resolution        : 2560x1440

====== ADAPTER =====
Device Name      : NVIDIA GeForce RTX 4090
Device Vendor ID : 0x000010DE
Device Device ID : 0x00002684
Device Video Mem : 24142 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 30719 MiB

The cloud provider also provides gaming-purpose GPU virtual machines. I noticed they also used the Parsec VDD as the output display but I don't know how. I can also create another display via moonlight but not RDP.

**Comment by bigruid** [comment]
same issue

**Comment by yqs112358** [comment]
Same issue too 🫠

**Comment by nomi-san** [comment]
Closed, moved to #82.
