### ISSUE TITLE
A step-by-step guide for who don't know code

### ISSUE THREAD

**Issue by chrisslatte** [nomi-san/parsec-vdd#3]
I only had some experience in matlab to support scientific work, the current read.me, issues and demo.cc excced the my capability,

Is it possible for you to make a step-by-step guide that anyone can follow?  e.g.  just typing-in code in console？

I would be really appreciated if you can do that. :)

**Comment by nomi-san** [comment]
What's your exciting about this repo? A virtual super display?

There will have no code explanation, the demo.cc is very basic, just focus on main() function and follow the pseudo code in readme. Then simply build demo.cc as a C++ program.
