### ISSUE TITLE
[Feature requests] Multi-language support 

### ISSUE THREAD

**Issue by shikkoku** [nomi-san/parsec-vdd#30]
Is it possible to add multi-language support in the future?

**Comment by nomi-san** [comment]
@shikkoku I have added multi-language support
Now you can make a new translation by creating a new file `app/Language/zh-cn.xaml`, then copy en.xaml content and modify it.

```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:system="clr-namespace:System;assembly=mscorlib"
>
    <system:String x:Key="lang_name">中文</system:String>
    ...
```

When the task is done, just rebuild the app.
Try the latest auto-build here: https://github.com/nomi-san/parsec-vdd/actions

![image](https://github.com/nomi-san/parsec-vdd/assets/38210249/a4d3f1ec-5262-46a4-9743-836b7e410441)
