### ISSUE TITLE
Subject: [Feature requests] Fixing the name of the generated virtual screen

### ISSUE THREAD

**Issue by ccddos** [nomi-san/parsec-vdd#32]
I would like to request a feature to fix the name of the generated virtual screen in the program I am using to extend my screen to a tablet. Currently, when setting up the display in Sunshine, I can specify the name of the display, which is convenient for quick setup.

However, the issue I am facing is that the new display is assigned a random name in the format .\DISPLAY{id}, where the "id" part is randomly generated during the screen generation process.

I kindly request an improvement in the program to provide a fixed name for the generated virtual screen, rather than the randomly assigned name. This would greatly enhance the usability and convenience of the program.
Thank you for considering my feature request. I look forward to your positive response.

**Comment by nomi-san** [comment]
Whats name as you desired, and how is it showing in Shunshine? Give me example and screenshots.
Note that the `{id}` is fixed by VDD install order, possible to change the visible name in the app, but other display names are be fixed by the driver as below.

```
ID: PSCCDD0
Name: ParsecVDA
Friendly Name: Parsec Virtual Display Adapter.
```

**Comment by ccddos** [comment]
I mean that although the specific name isn't critical, having a fixed name is essential. In this section, I can designate which display will be utilized when the Moonlight client connects to Sunshine.

Regarding the Parsec-VDD, my display configuration doesn't persist after a reboot, necessitating recreation of the display each time, and the display name is changed.

I'm using the installer version of Parsec-VDD, and the "run on startup" option isn't enabled.

![image](https://github.com/nomi-san/parsec-vdd/assets/135016091/9c82d681-413c-45d4-80a0-28c5114b1f98)

**Comment by nomi-san** [comment]
Got it. You shoud find a way to get the correct ID dynamically after the display is added and put it in Sunshine config. However the next CLI version should help you.

**Comment by nomi-san** [comment]
https://www.reddit.com/r/MoonlightStreaming/comments/193j5uc/dxgiinfoexe_reports_back_different_output_names/

**Comment by ccddos** [comment]
got it, Thanks
