### ISSUE TITLE
I did not see ParsecVDisplay v0.45.1 download resources

### ISSUE THREAD

**Issue by e2ee2** [nomi-san/parsec-vdd#33]
![微信截图_20240505172330](https://github.com/nomi-san/parsec-vdd/assets/15869679/8ad04081-dbb9-4e8c-bbd9-e49fab8e59d6)

**Comment by nomi-san** [comment]
Duplicate #31 
v0.45.1 is renamed from old v0.45-a tag

**Comment by e2ee2** [comment]
Okay, looking forward to the new version being released. Thank you very much
