### ISSUE TITLE
Add display and the new one disappear soon

### ISSUE THREAD

**Issue by harvey-woo** [nomi-san/parsec-vdd#38]
I can't create new display

When i click the `ADD DISPLAY` button, the new one show it's name `\\.\DISPLAY1`, And it disappear soon

It's suppose to be incorrect which conflicted with my main display (laptop)

But i click `ADD DISPLAY` in a short period of time. I can create two display, but they will not disappear

**Comment by nomi-san** [comment]
Which version is your Windows?
Try installing v0.41 driver: https://builds.parsec.app/vdd/parsec-vdd-0.41.0.0.exe

**Comment by HaoTian22** [comment]
I encountered this problem, too. On parsec-vdd 0.45 and Windows 11 Pro 22635.3930

**Comment by erwin-amigo** [comment]
Same thing happens to me ParsecVDisplay removes the newly added virtual monitor when I open google chrome, I already reinstalled and restarted. Any tips on the workaround?

**Comment by nomi-san** [comment]
@erwin-amigo 
> removes the newly added virtual monitor when I open google chrome

Did you see any flashing or black flickering when hovering some topbar buttons on Chrome. That behaviour will cause your GPU device to reset and all virtual displays should be removed.

**Comment by nomi-san** [comment]
Closed, duplicate #40 #58.
