### ISSUE TITLE
All icons moved to second display - Win10 主显示器问题

### ISSUE THREAD

**Issue by gaobingbing** [nomi-san/parsec-vdd#39]
添加了虚拟显示器后，无论是否设置主显示器，桌面及打开的应用始终在虚拟显示器，这是怎么回事？

**Comment by gaobingbing** [comment]
Windows 10 家庭中文版 19045.4412

**Comment by gaobingbing** [comment]
没有使用虚拟显示器，win10的逻辑是是跟着主显示器走的，当设置为主显示器的时候，桌面图标及任务栏都在主显示器上面的。

**Comment by nomi-san** [comment]
You should remove all unused/unplugged display devices e.g by using IOBit Driver Booster.
Then add a single virtual display, and make sure your physical display is main.

**Comment by gaobingbing** [comment]
![主屏幕1](https://github.com/nomi-san/parsec-vdd/assets/5975068/04f655ff-345a-4ce3-a648-bb314826f9a9)
![虚拟屏幕2](https://github.com/nomi-san/parsec-vdd/assets/5975068/60da95dd-8ccd-4bbb-9e05-27b1870afd15)
按照您说的试了，桌面应用图标还是在虚拟屏幕上面

**Comment by nomi-san** [comment]
Okay that is not caused by the virtual display, you have encountered a bug that all icons moved to second display. Your second screenshot didn't show taskbar items, that's normal, so you just need to move all icons to the main display.
