### ISSUE TITLE
Is there an option for users to customize specific resolutions and refresh rates?

### ISSUE THREAD

**Issue by KtzeAbyss** [nomi-san/parsec-vdd#4]
Although a wide variety of resolutions and refresh rates are currently supported, is there an option for users to customize specific resolutions and refresh rates? I'm leveraging this solution to use my tablet as a secondary screen, but my tablet has an unconventional resolution ratio. I'd really appreciate the capability to customize both the resolution and refresh rate. Moreover, the official manual for the driver mentions customization through the registry, but I'm unsure if this project follows the same guideline. After installing the driver, I couldn't find the registry path mentioned in the official documentation on my computer（https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration）

**Comment by nomi-san** [comment]
>  I couldn't find the registry path

I have not tried this ParsecVDD's registry guide, but you can create the path manually.

In additional, when changing the FPS in Parsec app, it will also change the display refresh rate using win32 API. This method could be found on stackoverflow.

**Comment by KtzeAbyss** [comment]
I'll give that a shot. By the way, is there a way to add multiple virtual displays?

**Comment by nomi-san** [comment]
@KtzeAbyss
I have updated the README and added new core API, check it out.
There's only a simple demo, you can use it to update your app,
or just wait for my complete app with translation support.

Also will have a modified driver to support HDR.
