### ISSUE TITLE
Set a very high resolution by mistake then unable to add new virtual display

### ISSUE THREAD

**Issue by MrJibus** [nomi-san/parsec-vdd#43]
I have setup by mistake a very high resolution which Parsec does not support.

Even when uninstalling / reinstalling Parsec-vdd, as soon as I try to add a new virtual display, it set immediately at the very high resolution i use to set before.

Tried to removed several files in app data. Same thing.

**Comment by dimon222** [comment]
Reboot of OS I think gets rid of these parsec displays.

**Comment by nomi-san** [comment]
Relates to #23.
Please delete this registry key or use a 3rd party app to clean all unused/unplugged devices before adding a new one.

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Connectivity
```

![image](https://github.com/nomi-san/parsec-vdd/assets/38210249/b76ad343-ce14-4049-8f2a-0a3d5b307d0d)

**Comment by MrJibus** [comment]
Thank you !
