### ISSUE TITLE
Intermittent Virtual Display Disconnections with Parsec-vdd on Windows 10 22H2

### ISSUE THREAD

**Issue by devh0407** [nomi-san/parsec-vdd#45]
I am encountering a recurring issue on my Windows 10 system where virtual displays created by Parsec-vdd are unexpectedly removed after a period of use. 

This problem occurs when I use Sunshine as a streaming source for an older tablet running Moonlight. 

> Although I am not certain that Sunshine is directly related to this issue, I primarily use Parsec-vdd in conjunction with Sunshine, which could suggest a possible connection.

When I used `eventvwr.msc` and checked the `Windows Logs / System`  for clues, the only anomalies around the times of the display disconnections were some TLS error logs, which seem unrelated.

Could you assist me in identifying the potential causes of these disconnections? 

Are there specific logs or diagnostic tools within Windows that I could utilize to gather more information and troubleshoot this issue more effectively? Additionally, if there are any steps I can take to specifically isolate and rule out the influence of Sunshine on this problem, that would be immensely helpful.

**System Specifications:**

OS: Windows 10 version 22H2, Build 19045.3803
Parsec-vdd version: v0.45.0
Hardware: Intel i5-10500 + AMD RX6400, with two physical Dell P2319H monitors connected to the RX6400

---
I would also like to commend you on the excellent functionality of Parsec-vdd—it has proven extremely useful and efficient in most scenarios.

**Comment by devh0407** [comment]
During a recent instance when the virtual display was automatically removed, 
I observed that the **GPU load spiked to 100%** in Windows 10 Task Manager just at the moment of removal. The computer then experienced a brief stutter before the virtual display was removed.

**Comment by nomi-san** [comment]
You should recheck the Sunshine's log, if you see something likes `device lost`, I'm sure that's caused by your driver (often on AMD). When the driver starts resetting the device due to error, the VDD will encounter problem too (may appear a caution icon in Device Manager above display adapter).

> I am encountering a recurring issue on my Windows 10 system where virtual displays created by Parsec-vdd are unexpectedly removed after a period of use.

For sure, you can use Parsec to host your PC with VDD (quit Sunshine, use Parsec's Fallback display option and unplug your all physical displays, then connect to the host with Parsec client).

> When I used eventvwr.msc and checked the Windows Logs / System for clues, the only anomalies around the times of the display disconnections were some TLS error logs, which seem unrelated.

I never see any event logs about unplugging of VDD.

> I observed that the GPU load spiked to 100% in Windows 10 Task Manager just at the moment of removal.

That's normal behaviour of device lost.

> The computer then experienced a brief stutter before the virtual display was removed.

Yeah, that occurs when you unplug a display.

**Comment by devh0407** [comment]
> You should recheck the Sunshine's log, if you see something likes `device lost`, I'm sure that's caused by your driver (often on AMD). When the driver starts resetting the device due to error, the VDD will encounter problem too (may appear a caution icon in Device Manager above display adapter).
> 
> > I am encountering a recurring issue on my Windows 10 system where virtual displays created by Parsec-vdd are unexpectedly removed after a period of use.
> 
> For sure, you can use Parsec to host your PC with VDD (quit Sunshine, use Parsec's Fallback display option and unplug your all physical displays, then connect to the host with Parsec client).
> 
> > When I used eventvwr.msc and checked the Windows Logs / System for clues, the only anomalies around the times of the display disconnections were some TLS error logs, which seem unrelated.
> 
> I never see any event logs about unplugging of VDD.
> 
> > I observed that the GPU load spiked to 100% in Windows 10 Task Manager just at the moment of removal.
> 
> That's normal behaviour of device lost.
> 
> > The computer then experienced a brief stutter before the virtual display was removed.
> 
> Yeah, that occurs when you unplug a display.
Thank you for your response.

I've looked into the Sunshine logs, and during the instance when the Virtual Display Driver (VDD) was removed, I noticed an error message stating "Failed to locate an output device," but there were no entries related to a 'device lost' event. This leads me to suspect that there might be a connection with my hardware setup. Interestingly, during the last removal of the VDD, I had two Electron applications running, which both threw renderer errors, though I couldn't pinpoint the exact cause of these errors.

I haven't used Parsec before, primarily due to network constraints, but I plan to test this setup on a local network machine to see if the problem persists.

Thanks again for your assistance.
