### ISSUE TITLE
How to make a screen work on specific GPU?

### ISSUE THREAD

**Issue by gehaoyu-cn** [nomi-san/parsec-vdd#47]
Hi, thank you for you work. I have a issue about multi GPUs. I have four GPUs and I add four screen. I run some andriod simulators on the screen. I found total four screen load on one single GPU. Is there a way to make a screen work on specific GPU? I want the four screen load average on each GPU. 
Thank you. Wish you a good day.

**Comment by nomi-san** [comment]
As I said in #46 about selecting parent GPU, you should find the **Vendor ID** of your GPU. But I'm not sure VDD can support a specific GPU per virtual display.

Run this program to enumerate your GPUs: [enum_dxgi.zip](https://github.com/user-attachments/files/15928440/enum_dxgi.zip)

```
Adapter (1): AMD Radeon(TM) Graphics
  LUID: 0x20F88
  Vendor ID: 0x1002
  Device ID: 0x1638
```

I don't have any device that has multiple GPUs to support your case, so do it yourself. Note that my app does not support multiple VDD adapters, you should modify the source code to run multiple instances and install multiple VDD adapters via devcon/nefcon. Then follow [this guide](https://support.parsec.app/hc/en-us/articles/4423615425293-VDD-Advanced-Configuration#parent_gpu) to set Vendor ID before pluggin a virtual display for each VDD.

In case of multiple GPUs have the same Vendor ID (AMD - 0x1002, NVIDIA - 0x10DE), the issue cant be solved with VDD. I see you have opened the same issue in https://github.com/itsmikethetech/Virtual-Display-Driver/issues/110, that's open source project and easy to solve your case.

**Comment by itsmikethetech** [comment]
Latest HDR beta has this implemented, but may be buggy. Please let us know how it works. https://github.com/itsmikethetech/Virtual-Display-Driver/releases/tag/24.7.18HDR

**Comment by maxpaynebupt** [comment]
I have two 3090, but, don't know why there are 3, and it seems to use the LUID, it's unique.

D:\>enum_dxgi.exe
Adapter (0): NVIDIA GeForce RTX 3090
  LUID: 0x1524C
  Vendor ID: 0x10DE
  Device ID: 0x2204
Adapter (1): NVIDIA GeForce RTX 3090
  LUID: 0x141B5
  Vendor ID: 0x10DE
  Device ID: 0x2204
Adapter (2): NVIDIA GeForce RTX 3090
  LUID: 0xA5C85
  Vendor ID: 0x10DE
  Device ID: 0x2204

**Comment by fr1g** [comment]
seems i now need to rely on anyone else that can give a pull request for this function.
really needed an item in per screen right mouse button menu that can switch the VD between detected GPUs

btw, I'm using R5 7600x with RX560D and seems these can work together. And RX560D is really sucks and when I swinging my mouse in VD which connected by sunshine, the local machine processing latency went up and so did the GPU usage

**Comment by nomi-san** [comment]
@fr1g that's impossible with Parsec VDD, it allows parent GPU selection in v0.45 but for AMD/NVIDIA, and cannot switch immediately without restarting device/adapter. Note that the driver is closed source, you should look at [itsmikethetech's virtual display](https://github.com/itsmikethetech/Virtual-Display-Driver).

**Comment by fr1g** [comment]
> @fr1g that's impossible with Parsec VDD, it allows parent GPU selection in v0.45 but for AMD/NVIDIA, and cannot switch immediately without restarting device/adapter. Note that the driver is closed source, you should look at [itsmikethetech's virtual display](https://github.com/itsmikethetech/Virtual-Display-Driver).

usable and fulfilled my needs (though they seems not providing an independent manager GUI)
