### ISSUE TITLE
Can parsec-vdd set resolution to 2240*1400 (16:10)?

### ISSUE THREAD

**Issue by Qynklee** [nomi-san/parsec-vdd#54]
I try to set virtual display to 2240*1400 (16:10) but no options to do this. How can I do it or add custom resolution to parsec-vdd?

**Comment by nomi-san** [comment]
Did you try the 'Custom function'? Click Custom... and add your custom resolution then press Apply.
This 2240x1400 (2K 16:10) is under 4K so it works properly.

![image](https://github.com/user-attachments/assets/b80004fe-122a-4ecc-a914-318f48bf1a2f)
