### ISSUE TITLE
Custom resolution cannot take effect

### ISSUE THREAD

**Issue by hututuo** [nomi-san/parsec-vdd#57]
The custom resolution has been set, but there is no response when the custom resolution is selected after creating the monitor (the options in the right-click menu have been changed, but the actual resolution has not been changed)thanks

https://github.com/user-attachments/assets/416c4dd9-d8f2-4e41-b120-b34efc39cfed

**Comment by nomi-san** [comment]
You have to add a new virtual display after applied your custom resolutions.

**Comment by hututuo** [comment]
> You have to add a new virtual display after applied your custom resolutions.

In the video I just add the custom resolution before adding the virtual screen, and I've tried adding multiple virtual screens after the setup is complete, but this doesn't work

**Comment by nomi-san** [comment]
You should set resolution in Windows Display Settings, the app cannot apply it (some sizes not divisible by 10).

![image](https://github.com/user-attachments/assets/aa8a4dd5-7fff-4f2b-b21a-3d3c0e1810e5)
