### ISSUE TITLE
Can't add more than 3 virtual displays, All will get removed immediately?

### ISSUE THREAD

**Issue by Xiao-0417** [nomi-san/parsec-vdd#58]
Dear author, After copying your latest code repository and completing some missing code, I found that I can only add three virtual displays to my device. When I add the fourth one, all displays will be deleted one by one. At the same time, the debugging window will display that the process has been destroyed
Then when I tried to locate the abnormal location, I found an identifier related to Thread in the **Program.cs**. After removing it, I was able to add five virtual displays, but when I added the sixth one, the display was still completely removed.
So I want to know why did this situation occur? During my debugging process, I found that the functions related to deleting the display were not called, and I did not find any exceptions. So I am very curious why this question arises, and I sincerely hope you can reply. Thank you

**Comment by nomi-san** [comment]
The latest code uses Winforms Timer to ping to the VDD. When you add a new display, the message loop will get stuck a second and longer with more present displays, then the update timer goes off too, all added displays will be removed. I'll fix soon.

**Comment by nomi-san** [comment]
Fixed, related to #40.
