### ISSUE TITLE
I’m wondering if a virtual display can function as the only display without a physical monitor connected to the computer. 

### ISSUE THREAD

**Issue by LiquidTaeJa** [nomi-san/parsec-vdd#59]
I’m wondering if a virtual display can function as the only display without a physical monitor connected to the computer. Specifically, if I initially set up the virtual display using Parsec-VDD with a physical monitor connected, then disconnect the monitor, will the virtual display still be operational?

Additionally, if I connect to the computer through a remote control app like Moonlight after disconnecting the monitor, would the virtual display continue to work in that scenario?

I’m currently using a laptop and can't test this myself, so I’m reaching out to see if anyone has tried this and can confirm whether it works.

Thanks in advance for your help!

**Comment by nomi-san** [comment]
Yesh, just enable the 'fallback display' option and allow the app to run on startup, your headless PC will be able to connect from any remote desktop app.

**Comment by LiquidTaeJa** [comment]
That's great! It has helped me a lot. I'd like to thank you for you development.
