### ISSUE TITLE
Could the project will compatible for Linux like Debian in the future?

### ISSUE THREAD

**Issue by gix9303** [nomi-san/parsec-vdd#60]
like the title saying

**Comment by nomi-san** [comment]
No. This VDD is designed for Windows only. But found a great anwser [on Reddit](https://www.reddit.com/r/linux4noobs/comments/1bmiigy/comment/kwc9p0l/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button):

> The tool deskreen https://deskreen.com/lang-en has some details in its docs/faq about how to generate a 'virtual' display, you can then share via vnc or other methods (like deskreen) to other devices on the network.

> https://github.com/pavlobu/deskreen/discussions/86
> https://github.com/dianariyanto/virtual-display-linux
> https://askubuntu.com/questions/453109/add-fake-display-when-no-monitor-is-plugged-in

> Having a HDMI dongle is not required, but it can make things a whole lot easier.
