### ISSUE TITLE
Can you provide a dll version

### ISSUE THREAD

**Issue by telppa** [nomi-san/parsec-vdd#7]
This will allow more people to call it in their favorite language!

**Comment by nomi-san** [comment]
That's no meaning when you already have the C/C++ source code.

Btw, building a DLL is quite easy, and my header is fully compatible with C.

1. Create a new `main.c` that includes the core header.

```c
#include "parsec-vdd.h"
```

2. List API functions in a `exports.def`.

```py
EXPORTS
  OpenDeviceHandle
  VddAddDisplay
  VddRemoveDisplay
  # etc
```

3. Build the DLL, e.g with MSVC `CL.exe`.

```
cl /LD /OUT:parsec-vdd.dll main.c /link /DEF:exports.def
```

**Comment by WinkelCode** [comment]
I have a slightly related question, do you happen to know if there is an interface for the Parsec driver to get access to the swapchain? (https://learn.microsoft.com/en-us/windows-hardware/drivers/display/iddcx-objects)

I've been playing around with the idea of writing a thing using the IDD functionality and directly grabbing the image off of there, rather than relying on other capture APIs.

**Comment by nomi-san** [comment]
@WinkelCode 

Parsec VDD doesn't have any interface to obtain the swapchain from the outside. You should write your own IddCx driver, then access the dxgi swapchain to process the desktop image. But I think capturing desktop with native-gpu encoders are lower level than Idd, Parsec host also uses this method to capture the entire desktop.

```mermaid
graph LR
A[idd] --> B[dxgi] --> |post-process| C[output]
B .->|encode| D[streaming]

Z[gpu] <-..-> B
```

There are alot of sample projects that can be found in the README.
- [microsoft/Windows-driver-samples/video/IndirectDisplay/IddSampleDriver/Driver.cpp#L368](https://github.com/microsoft/Windows-driver-samples/blob/b3af8c8f9bd508f54075da2f2516b31d05cd52c8/video/IndirectDisplay/IddSampleDriver/Driver.cpp#L368)
- [MolotovCherry/virtual-display-rs/rust/virtual-display-driver/src/swap_chain_processor.rs#L85](https://github.com/MolotovCherry/virtual-display-rs/blob/eae5120a676831ebb96a78125f7e84532bcaf152/rust/virtual-display-driver/src/swap_chain_processor.rs#L85)
