### ISSUE TITLE
Option to start minimized

### ISSUE THREAD

**Issue by OneCyrus** [nomi-san/parsec-vdd#76]
there should be an option to run parsec-vsd minimized/closed without showing the UI on startup.

**Comment by nomi-san** [comment]
Add `-silent` to the exe shortcut, but didn't it run on startup silently?

**Comment by tdbe** [comment]
The only way to get Parsec to start minimized: `"C:\Program Files\Parsec\parsecd.exe" app_silent=1` - exactly like this, not with `-` or `--`
