### ISSUE TITLE
"Relatively" high CPU usage from ParsecVDisplay.exe when in background

### ISSUE THREAD

**Issue by WinkelCode** [nomi-san/parsec-vdd#81]
<img width="419" alt="Screenshot from Task Manager showing 0.5% CPU utilization of a program called ParsecVDisplay" src="https://github.com/user-attachments/assets/cc7e7214-34ef-4c25-93e6-9abd0d38e26c" />

I am using this build: https://github.com/nomi-san/parsec-vdd/actions/runs/12344872549

My CPU is an AMD Ryzen 9 5900X.

0.5% isn't much in the grand scheme of things, but since the program will be running 24/7 on some machines, it should be fully idling in the background, even if just for power savings and environmental impact. I also tested the "core" CLI program, which idles at 0% CPU utilization.

**Comment by nomi-san** [comment]
This build includes realtime driver monitoring, I also increase the sleep time to 1 second but it always costs up to a half percent. I'm finding a better solution or will remove this monitoring soon.

**Comment by WinkelCode** [comment]
CPU usage seems normal now 👍
